[workspace]
authors = ["dacher <mael.dacher@student.isae-supaero.fr>"]
channels = ["conda-forge"]
name = "hackaton_feature_engineering"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.9,<3.14"
pytorch = ">=2.8.0,<3"
pandas = ">=2.3.3,<3"
numpy = ">=2.3.4,<3"
scikit-learn = ">=1.7.2,<2"
